// This file is Copyright its original authors, visible in version control history.
//
// This file is licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. You may not use this file except in
// accordance with one or both of these licenses.

//! Holds a payment handler allowing to send and receive on-chain payments.

use std::collections::HashSet;
use std::sync::{Arc, Mutex, RwLock};

use bitcoin::{Address, OutPoint, Transaction, Txid};

use crate::chain::{BroadcastResponse, ChainSource};
use crate::config::{AddressType, Config, OnchainWalletAccount};
use crate::error::Error;
use crate::fee_estimator::ConfirmationTarget;
use crate::logger::{log_info, LdkLogger, Logger};
use crate::runtime::RuntimeControl;
use crate::types::{ChannelManager, SpendableUtxo, Wallet};
use crate::wallet::{CoinSelectionAlgorithm, OnchainSendAmount};

#[cfg(not(feature = "uniffi"))]
type FeeRate = bitcoin::FeeRate;
#[cfg(feature = "uniffi")]
type FeeRate = Arc<bitcoin::FeeRate>;

macro_rules! maybe_map_fee_rate_opt {
	($fee_rate_opt:expr) => {{
		#[cfg(not(feature = "uniffi"))]
		{
			$fee_rate_opt
		}
		#[cfg(feature = "uniffi")]
		{
			$fee_rate_opt.map(|f| *f)
		}
	}};
}

/// The keychain an address was derived from.
///
/// Address derivation APIs can use [`KeychainKind::External`] for receive addresses or
/// [`KeychainKind::Internal`] for change addresses. APIs that generate or reveal new receive
/// addresses always operate on [`KeychainKind::External`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeychainKind {
	/// External receive-address keychain.
	External,
	/// Internal change-address keychain.
	Internal,
}

impl From<bdk_wallet::KeychainKind> for KeychainKind {
	fn from(keychain: bdk_wallet::KeychainKind) -> Self {
		match keychain {
			bdk_wallet::KeychainKind::External => Self::External,
			bdk_wallet::KeychainKind::Internal => Self::Internal,
		}
	}
}

impl From<KeychainKind> for bdk_wallet::KeychainKind {
	fn from(keychain: KeychainKind) -> Self {
		match keychain {
			KeychainKind::External => Self::External,
			KeychainKind::Internal => Self::Internal,
		}
	}
}

/// Metadata for an address derived by the on-chain wallet.
///
/// The `index` is the BIP32 child index within `keychain`. For receive addresses generated by
/// `new_address_info` methods, `keychain` is expected to be [`KeychainKind::External`].
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AddressInfo {
	/// Child index of this address within its keychain.
	pub index: u32,
	/// The derived Bitcoin address.
	pub address: Address,
	/// The keychain this address belongs to.
	pub keychain: KeychainKind,
}

impl From<bdk_wallet::AddressInfo> for AddressInfo {
	fn from(address_info: bdk_wallet::AddressInfo) -> Self {
		Self {
			index: address_info.index,
			address: address_info.address,
			keychain: address_info.keychain.into(),
		}
	}
}

/// A payment handler allowing to send and receive on-chain payments.
///
/// Should be retrieved by calling [`Node::onchain_payment`].
///
/// [`Node::onchain_payment`]: crate::Node::onchain_payment
pub struct OnchainPayment {
	runtime: Arc<RuntimeControl>,
	chain_source: Arc<ChainSource>,
	wallet: Arc<Wallet>,
	channel_manager: Arc<ChannelManager>,
	config: Arc<Config>,
	is_running: Arc<RwLock<bool>>,
	logger: Arc<Logger>,
}

/// Result of one direct backend submission of a locally created on-chain transaction.
/// A returned txid identifies the attempt; only `Accepted` means backend acknowledgement.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OnchainSendResult {
	/// The configured backend acknowledged this transaction, without guaranteeing confirmation.
	Accepted {
		/// Locally computed transaction ID acknowledged by the backend.
		txid: Txid,
	},
	/// A recognized refusal response was received; earlier delivery is still possible.
	Rejected {
		/// Locally computed transaction ID that received a refusal response.
		txid: Txid,
		/// Diagnostic refusal reported by the backend.
		reason: String,
	},
	/// The backend's acceptance is indeterminate. Never infer retry safety from this.
	Unknown {
		/// Locally computed transaction ID whose broadcast result is unknown.
		txid: Txid,
	},
}

fn check_send_context(is_running: &RwLock<bool>) -> Result<(), Error> {
	if !*is_running.read().unwrap() {
		return Err(Error::NotRunning);
	}
	// Synchronous broadcast cannot block a current-thread Tokio runtime.
	if tokio::runtime::Handle::try_current()
		.is_ok_and(|handle| handle.runtime_flavor() == tokio::runtime::RuntimeFlavor::CurrentThread)
	{
		return Err(Error::PaymentSendingFailed);
	}
	Ok(())
}

fn validate_selected_outpoints(outpoints: &[OutPoint]) -> Result<(), Error> {
	if outpoints.is_empty() || outpoints.iter().collect::<HashSet<_>>().len() != outpoints.len() {
		return Err(Error::WalletOperationFailed);
	}
	Ok(())
}

fn validate_signed_inputs(tx: &Transaction, outpoints: &[OutPoint]) -> Result<(), Error> {
	validate_selected_outpoints(outpoints)?;
	let signed: HashSet<_> = tx.input.iter().map(|input| input.previous_output).collect();
	if tx.input.len() != outpoints.len() || signed != outpoints.iter().copied().collect() {
		return Err(Error::OnchainTxCreationFailed);
	}
	Ok(())
}

/// An in-memory signed candidate that has not been submitted by preparation.
///
/// Persist its actual txid, inputs and recipient amount under the original wallet/payment
/// identity before calling [`Self::broadcast`]. Dropping this object does not broadcast.
/// It does not persist a transaction journal or restore signed transactions after restart.
pub struct PreparedOnchainSend {
	tx: Transaction,
	recipient_amount_sats: u64,
	runtime: Arc<RuntimeControl>,
	chain_source: Arc<ChainSource>,
	is_running: Arc<RwLock<bool>>,
	result: Mutex<Option<Result<OnchainSendResult, Error>>>,
}

impl PreparedOnchainSend {
	/// Return the actual signed candidate's locally computed transaction ID.
	pub fn txid(&self) -> Txid {
		self.tx.compute_txid()
	}

	/// Return the actual signed input outpoints, independent of caller-supplied value hints.
	pub fn inputs(&self) -> Vec<OutPoint> {
		self.tx.input.iter().map(|input| input.previous_output).collect()
	}

	/// Return the sum of signed outputs paying the requested recipient script.
	pub fn recipient_amount_sats(&self) -> u64 {
		self.recipient_amount_sats
	}

	/// Submit this exact candidate through the configured backend once.
	///
	/// Calls on the same object are serialized and return its cached result. The backend's
	/// transport may retry the same bytes. `Err` proves this invocation did not dispatch;
	/// neither `Rejected` nor `Unknown` authorizes clearing the original payment guard.
	/// The caller must durably record candidate provenance before its first call.
	pub fn broadcast(&self) -> Result<OnchainSendResult, Error> {
		let mut cached = self.result.lock().unwrap();
		if let Some(result) = cached.as_ref() {
			return result.clone();
		}
		check_send_context(&self.is_running)?;
		let source = Arc::clone(&self.chain_source);
		let tx = self.tx.clone();
		let result = self
			.runtime
			.try_block_on(async move { source.broadcast_user_transaction(&tx).await })
			.and_then(|response| response)
			.map(|response| match response {
				BroadcastResponse::Accepted => OnchainSendResult::Accepted { txid: self.txid() },
				BroadcastResponse::Rejected(reason) => {
					OnchainSendResult::Rejected { txid: self.txid(), reason }
				},
				BroadcastResponse::Unknown => OnchainSendResult::Unknown { txid: self.txid() },
			});
		*cached = Some(result.clone());
		result
	}
}

impl OnchainPayment {
	pub(crate) fn new(
		runtime: Arc<RuntimeControl>, chain_source: Arc<ChainSource>, wallet: Arc<Wallet>,
		channel_manager: Arc<ChannelManager>, config: Arc<Config>, is_running: Arc<RwLock<bool>>,
		logger: Arc<Logger>,
	) -> Self {
		Self { runtime, chain_source, wallet, channel_manager, config, is_running, logger }
	}

	fn prepare_send(
		&self, address: &Address, send_amount: OnchainSendAmount, fee_rate: Option<FeeRate>,
		utxos_to_spend: Option<Vec<OutPoint>>,
	) -> Result<Arc<PreparedOnchainSend>, Error> {
		check_send_context(&self.is_running)?;
		if let Some(outpoints) = &utxos_to_spend {
			validate_selected_outpoints(outpoints)?;
		}
		let tx = self.wallet.prepare_send_to_address(
			address,
			send_amount,
			maybe_map_fee_rate_opt!(fee_rate),
			utxos_to_spend.clone(),
			&self.channel_manager,
		)?;
		if let Some(outpoints) = &utxos_to_spend {
			validate_signed_inputs(&tx, outpoints)?;
		}
		let actual_inputs: Vec<_> = tx.input.iter().map(|input| input.previous_output).collect();
		validate_selected_outpoints(&actual_inputs).map_err(|_| Error::OnchainTxCreationFailed)?;
		let recipient_script = address.script_pubkey();
		let recipient_amount_sats = tx
			.output
			.iter()
			.filter(|output| output.script_pubkey == recipient_script)
			.try_fold(0u64, |total, output| total.checked_add(output.value.to_sat()))
			.ok_or(Error::OnchainTxCreationFailed)?;
		Ok(Arc::new(PreparedOnchainSend {
			tx,
			recipient_amount_sats,
			runtime: Arc::clone(&self.runtime),
			chain_source: Arc::clone(&self.chain_source),
			is_running: Arc::clone(&self.is_running),
			result: Mutex::new(None),
		}))
	}

	fn send_with_broadcast_result(
		&self, address: &Address, send_amount: OnchainSendAmount, fee_rate: Option<FeeRate>,
		utxos_to_spend: Option<Vec<OutPoint>>,
	) -> Result<OnchainSendResult, Error> {
		self.prepare_send(address, send_amount, fee_rate, utxos_to_spend)?.broadcast()
	}

	/// Retrieve a new on-chain/funding address.
	pub fn new_address(&self) -> Result<Address, Error> {
		let funding_address = self.wallet.get_new_address()?;
		log_info!(self.logger, "Generated new funding address: {}", funding_address);
		Ok(funding_address)
	}

	/// Retrieve a new on-chain/funding address with derivation metadata.
	///
	/// This uses the same default address type and receive cursor as [`new_address`].
	///
	/// [`new_address`]: Self::new_address
	pub fn new_address_info(&self) -> Result<AddressInfo, Error> {
		let funding_address_info = AddressInfo::from(self.wallet.get_new_address_info()?);
		log_info!(self.logger, "Generated new funding address: {}", funding_address_info.address);
		Ok(funding_address_info)
	}

	/// Retrieve a new on-chain address for a specific address type.
	pub fn new_address_for_type(&self, address_type: AddressType) -> Result<Address, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let funding_address = self.wallet.get_new_address_for_type(address_type)?;
		log_info!(
			self.logger,
			"Generated new funding address for {:?}: {}",
			address_type,
			funding_address
		);
		Ok(funding_address)
	}

	/// Retrieve a new on-chain address with derivation metadata for a specific address type.
	pub fn new_address_info_for_type(
		&self, address_type: AddressType,
	) -> Result<AddressInfo, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let funding_address_info =
			AddressInfo::from(self.wallet.get_new_address_info_for_type(address_type)?);
		log_info!(
			self.logger,
			"Generated new funding address for {:?}: {}",
			address_type,
			funding_address_info.address
		);
		Ok(funding_address_info)
	}

	/// Retrieve a new on-chain address for a specific wallet account.
	///
	/// An unloaded derived account returns [`Error::OnchainWalletAccountNotRegistered`].
	pub fn new_address_for_account(
		&self, address_type: AddressType, account_index: u32,
	) -> Result<Address, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let wallet_account = OnchainWalletAccount { address_type, account_index };
		let funding_address = self.wallet.get_new_address_for_account(wallet_account)?;
		log_info!(
			self.logger,
			"Generated new funding address for {:?}: {}",
			wallet_account,
			funding_address
		);
		Ok(funding_address)
	}

	/// Retrieve a new on-chain address with derivation metadata for a specific wallet account.
	///
	/// An unloaded derived account returns [`Error::OnchainWalletAccountNotRegistered`].
	pub fn new_address_info_for_account(
		&self, address_type: AddressType, account_index: u32,
	) -> Result<AddressInfo, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let wallet_account = OnchainWalletAccount { address_type, account_index };
		let funding_address_info =
			AddressInfo::from(self.wallet.get_new_address_info_for_account(wallet_account)?);
		log_info!(
			self.logger,
			"Generated new funding address for {:?}: {}",
			wallet_account,
			funding_address_info.address
		);
		Ok(funding_address_info)
	}

	/// Derive address metadata for `address_type`, `keychain`, and `index` on account `0`.
	///
	/// This does not reveal, reserve, or advance any wallet cursor.
	pub fn address_info_for_type_at_index(
		&self, address_type: AddressType, keychain: KeychainKind, index: u32,
	) -> Result<AddressInfo, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		self.wallet
			.get_address_info_for_type_at_index(address_type, keychain, index)
			.map(Into::into)
	}

	/// Derive address metadata for a wallet account without advancing its cursor.
	///
	/// An unloaded derived account returns [`Error::OnchainWalletAccountNotRegistered`].
	pub fn address_info_for_account_at_index(
		&self, address_type: AddressType, account_index: u32, keychain: KeychainKind, index: u32,
	) -> Result<AddressInfo, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let wallet_account = OnchainWalletAccount { address_type, account_index };
		self.wallet
			.get_address_info_for_account_at_index(wallet_account, keychain, index)
			.map(Into::into)
	}

	/// Derive address metadata for a contiguous account-`0` range without advancing any wallet
	/// cursor.
	///
	/// The returned vector contains `count` addresses starting at `start_index`. Batch requests are
	/// capped at 10,000 addresses per call.
	pub fn address_infos_for_type(
		&self, address_type: AddressType, keychain: KeychainKind, start_index: u32, count: u32,
	) -> Result<Vec<AddressInfo>, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		self.wallet
			.get_address_infos_for_type(address_type, keychain, start_index, count)
			.map(|infos| infos.into_iter().map(Into::into).collect())
	}

	/// Derive address metadata for a contiguous wallet-account range without advancing its cursor.
	///
	/// Batch requests are capped at 10,000 addresses per call.
	/// An unloaded derived account returns [`Error::OnchainWalletAccountNotRegistered`].
	pub fn address_infos_for_account(
		&self, address_type: AddressType, account_index: u32, keychain: KeychainKind,
		start_index: u32, count: u32,
	) -> Result<Vec<AddressInfo>, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let wallet_account = OnchainWalletAccount { address_type, account_index };
		self.wallet
			.get_address_infos_for_account(wallet_account, keychain, start_index, count)
			.map(|infos| infos.into_iter().map(Into::into).collect())
	}

	/// Reveal external receive addresses for account-`0` `address_type` up to and including
	/// `index`.
	///
	/// After this returns successfully, normal address generation for `address_type` will not return
	/// any receive address with an index at or below `index`.
	pub fn reveal_receive_addresses_to(
		&self, address_type: AddressType, index: u32,
	) -> Result<(), Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		self.wallet.reveal_receive_addresses_to(address_type, index)
	}

	/// Reveal external receive addresses through `index` for a specific wallet account.
	///
	/// Apps issuing addresses from an exported account xpub should call this with the highest issued
	/// index so wallet sync includes the corresponding scripts.
	/// An unloaded derived account returns [`Error::OnchainWalletAccountNotRegistered`].
	pub fn reveal_receive_addresses_to_account(
		&self, address_type: AddressType, account_index: u32, index: u32,
	) -> Result<(), Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let wallet_account = OnchainWalletAccount { address_type, account_index };
		self.wallet.reveal_receive_addresses_to_account(wallet_account, index)
	}

	/// Returns a list of all UTXOs that are safe to spend.
	///
	/// This excludes any outputs that are currently being used to fund Lightning channels.
	///
	/// **Note:** This does not account for anchor channel reserves. When using these UTXOs
	/// for transactions, ensure you maintain sufficient balance for any required reserves.
	pub fn list_spendable_outputs(&self) -> Result<Vec<SpendableUtxo>, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		self.wallet
			.get_spendable_utxos(&self.channel_manager)
			.map(|outputs| outputs.into_iter().map(SpendableUtxo::from).collect())
	}

	/// Select UTXOs using a specific coin selection algorithm.
	///
	/// This method allows you to choose which algorithm to use for selecting UTXOs
	/// to meet a target amount. The selected UTXOs will be safe to spend (not funding channels).
	///
	/// # Arguments
	///
	/// * `target_amount_sats` - The target amount in satoshis
	/// * `fee_rate` - The fee rate to use (or None to estimate)
	/// * `algorithm` - The coin selection algorithm to use
	/// * `utxos` - Optional list of UTXO outpoints to select from (or None to use all spendable UTXOs)
	pub fn select_utxos_with_algorithm(
		&self, target_amount_sats: u64, fee_rate: Option<FeeRate>,
		algorithm: CoinSelectionAlgorithm, utxos: Option<Vec<SpendableUtxo>>,
	) -> Result<Vec<SpendableUtxo>, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		// Get available UTXOs, optionally filtering by provided UTXOs
		let available_utxos = match utxos {
			Some(spendable_utxos) => {
				// Get all spendable UTXOs and filter by the provided UTXOs
				let wallet_outputs = self.wallet.get_spendable_utxos(&self.channel_manager)?;
				let outpoint_set: std::collections::HashSet<_> =
					spendable_utxos.iter().map(|u| u.outpoint).collect();
				wallet_outputs
					.into_iter()
					.filter(|output| outpoint_set.contains(&output.outpoint))
					.collect()
			},
			None => self.wallet.get_spendable_utxos(&self.channel_manager)?,
		};

		if available_utxos.is_empty() {
			return Err(Error::InsufficientFunds);
		}

		// Use the set fee_rate or default to fee estimation
		let confirmation_target = ConfirmationTarget::OnchainPayment;
		let fee_rate = maybe_map_fee_rate_opt!(fee_rate)
			.unwrap_or_else(|| self.wallet.estimate_fee_rate(confirmation_target));

		// Get a drain script (change address)
		let drain_script = self.wallet.get_drain_script()?;

		// Apply coin selection
		let selected_outpoints = self.wallet.select_utxos_with_algorithm(
			target_amount_sats,
			available_utxos.clone(),
			fee_rate,
			algorithm,
			&drain_script,
			&self.channel_manager,
		)?;

		// Convert selected outpoints back to SpendableUtxo by direct filtering
		let selected_utxos: Vec<SpendableUtxo> = available_utxos
			.into_iter()
			.filter(|utxo| selected_outpoints.contains(&utxo.outpoint))
			.map(SpendableUtxo::from)
			.collect();

		Ok(selected_utxos)
	}

	/// Calculates the total fee for an on-chain payment without sending it.
	///
	/// This method simulates creating a transaction to the given address for the specified amount
	/// and returns the total fee that would be paid. This is useful for displaying fee estimates
	/// to users before they confirm a transaction.
	///
	/// The calculation respects any on-chain reserve requirements and validates that sufficient
	/// funds are available, just like [`send_to_address`].
	///
	/// **Note on maximum amounts:** For calculating the fee when sending the entire spendable
	/// balance, prefer [`calculate_send_all_fee`] which is purpose-built for that use case.
	/// This method includes a best-effort fallback for near-max amounts, but it may not
	/// trigger in all cases depending on the underlying wallet error.
	///
	/// [`calculate_send_all_fee`]: Self::calculate_send_all_fee
	///
	/// # Arguments
	///
	/// * `address` - The Bitcoin address to send to
	/// * `amount_sats` - The amount to send in satoshis (or total balance for max send)
	/// * `fee_rate` - Optional fee rate to use (if None, will estimate based on current network conditions)
	/// * `utxos_to_spend` - Optional list of specific UTXOs to use for the transaction
	///
	/// # Returns
	///
	/// The total fee in satoshis that would be paid for this transaction.
	///
	/// # Errors
	///
	/// * [`Error::NotRunning`] - If the node is not running
	/// * [`Error::InvalidAddress`] - If the address is invalid
	/// * [`Error::InsufficientFunds`] - If there are insufficient funds for the payment
	/// * [`Error::WalletOperationFailed`] - If fee calculation fails
	///
	/// [`send_to_address`]: Self::send_to_address
	/// [`BalanceDetails::total_onchain_balance_sats`]: crate::balance::BalanceDetails::total_onchain_balance_sats
	pub fn calculate_total_fee(
		&self, address: &bitcoin::Address, amount_sats: u64, fee_rate: Option<FeeRate>,
		utxos_to_spend: Option<Vec<SpendableUtxo>>,
	) -> Result<u64, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let cur_anchor_reserve_sats =
			crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);

		// Get current balances
		let (_total_balance, spendable_balance) =
			self.wallet.get_balances(cur_anchor_reserve_sats).unwrap_or((0, 0));

		// First try with the exact amount
		let outpoints = utxos_to_spend.map(|utxos| utxos.into_iter().map(|u| u.outpoint).collect());
		let fee_rate_opt = maybe_map_fee_rate_opt!(fee_rate);

		// Try calculating with exact amount first
		let send_amount =
			OnchainSendAmount::ExactRetainingReserve { amount_sats, cur_anchor_reserve_sats };
		let result = self.wallet.calculate_transaction_fee(
			address,
			send_amount,
			fee_rate_opt,
			outpoints.clone(),
			&self.channel_manager,
		);

		// If we get InsufficientFunds and the amount is within the spendable balance,
		// try calculating as if sending all available funds
		if matches!(result, Err(Error::InsufficientFunds)) && amount_sats <= spendable_balance {
			// Try with AllRetainingReserve to calculate the fee for sending all
			let all_retaining = OnchainSendAmount::AllRetainingReserve { cur_anchor_reserve_sats };
			if let Ok(fee) = self.wallet.calculate_transaction_fee(
				address,
				all_retaining,
				fee_rate_opt,
				outpoints.clone(),
				&self.channel_manager,
			) {
				// Return the fee for sending all available funds
				return Ok(fee);
			}
		}

		result
	}

	/// Calculates the total fee for sending all available on-chain funds without
	/// actually broadcasting.
	///
	/// This is the fee-calculation counterpart of [`send_all_to_address`]. Use it to
	/// show the user how much a drain / send-all transaction would cost before they
	/// confirm.
	///
	/// When `retain_reserves` is `true`, the calculation accounts for the on-chain anchor
	/// channel reserve (see [`BalanceDetails::total_anchor_channels_reserve_sats`]), sending only
	/// the spendable portion. When `false`, the calculation covers draining the entire wallet
	/// balance, which may be dangerous if you have open anchor channels whose counterparty you
	/// don't trust to spend the anchor output after closure.
	///
	/// # Arguments
	///
	/// * `address` - The destination Bitcoin address
	/// * `retain_reserves` - If `true`, retains the anchor channel reserve; if `false`, drains everything
	/// * `fee_rate` - Optional fee rate to use (if `None`, will estimate based on current network conditions)
	///
	/// # Returns
	///
	/// The total fee in satoshis that would be paid for this transaction.
	///
	/// # Errors
	///
	/// * [`Error::NotRunning`] - If the node is not running
	/// * [`Error::InvalidAddress`] - If the address is invalid
	/// * [`Error::InsufficientFunds`] - If there are insufficient funds
	/// * [`Error::WalletOperationFailed`] - If fee calculation fails
	///
	/// [`send_all_to_address`]: Self::send_all_to_address
	/// [`BalanceDetails::total_anchor_channels_reserve_sats`]: crate::BalanceDetails::total_anchor_channels_reserve_sats
	pub fn calculate_send_all_fee(
		&self, address: &bitcoin::Address, retain_reserves: bool, fee_rate: Option<FeeRate>,
	) -> Result<u64, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let send_amount = if retain_reserves {
			let cur_anchor_reserve_sats =
				crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);
			OnchainSendAmount::AllRetainingReserve { cur_anchor_reserve_sats }
		} else {
			OnchainSendAmount::AllDrainingReserve
		};

		let fee_rate_opt = maybe_map_fee_rate_opt!(fee_rate);
		self.wallet.calculate_transaction_fee(
			address,
			send_amount,
			fee_rate_opt,
			None,
			&self.channel_manager,
		)
	}

	/// Send an on-chain payment to the given address.
	///
	/// This will respect any on-chain reserve we need to keep, i.e., won't allow to cut into
	/// [`BalanceDetails::total_anchor_channels_reserve_sats`].
	///
	/// If `fee_rate` is set it will be used on the resulting transaction. Otherwise we'll retrieve
	/// a reasonable estimate from the configured chain source.
	///
	/// This legacy method returns the locally computed txid after attempting to queue the signed
	/// transaction. Queue admission can fail without changing the returned txid.
	/// It does not report backend acceptance; use [`Self::send_to_address_with_broadcast_result`] when
	/// the caller needs that distinction.
	///
	/// [`BalanceDetails::total_anchor_channels_reserve_sats`]: crate::BalanceDetails::total_anchor_channels_reserve_sats
	pub fn send_to_address(
		&self, address: &bitcoin::Address, amount_sats: u64, fee_rate: Option<FeeRate>,
		utxos_to_spend: Option<Vec<SpendableUtxo>>,
	) -> Result<Txid, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let cur_anchor_reserve_sats =
			crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);
		let send_amount =
			OnchainSendAmount::ExactRetainingReserve { amount_sats, cur_anchor_reserve_sats };
		let outpoints = utxos_to_spend.map(|utxos| utxos.into_iter().map(|u| u.outpoint).collect());
		let fee_rate_opt = maybe_map_fee_rate_opt!(fee_rate);
		self.wallet.send_to_address(
			address,
			send_amount,
			fee_rate_opt,
			outpoints,
			&self.channel_manager,
		)
	}

	/// Send an on-chain payment to the given address, draining the available funds.
	///
	/// This is useful if you have closed all channels and want to migrate funds to another
	/// on-chain wallet.
	///
	/// To preview the fee before broadcasting, use [`calculate_send_all_fee`].
	///
	/// Please note that if `retain_reserves` is set to `false` this will **not** retain any on-chain reserves, which might be potentially
	/// dangerous if you have open Anchor channels for which you can't trust the counterparty to
	/// spend the Anchor output after channel closure. If `retain_reserves` is set to `true`, this
	/// will try to send all spendable onchain funds, i.e.,
	/// [`BalanceDetails::spendable_onchain_balance_sats`].
	///
	/// If `fee_rate` is set it will be used on the resulting transaction. Otherwise a reasonable
	/// we'll retrieve an estimate from the configured chain source.
	///
	/// This legacy method returns the locally computed txid after attempting to queue the signed
	/// transaction. Queue admission can fail without changing the returned txid.
	/// It does not report backend acceptance; use [`Self::send_all_to_address_with_broadcast_result`]
	/// when the caller needs that distinction.
	///
	/// [`calculate_send_all_fee`]: Self::calculate_send_all_fee
	/// [`BalanceDetails::spendable_onchain_balance_sats`]: crate::balance::BalanceDetails::spendable_onchain_balance_sats
	pub fn send_all_to_address(
		&self, address: &bitcoin::Address, retain_reserves: bool, fee_rate: Option<FeeRate>,
	) -> Result<Txid, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let send_amount = if retain_reserves {
			let cur_anchor_reserve_sats =
				crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);
			OnchainSendAmount::AllRetainingReserve { cur_anchor_reserve_sats }
		} else {
			OnchainSendAmount::AllDrainingReserve
		};

		let fee_rate_opt = maybe_map_fee_rate_opt!(fee_rate);
		self.wallet.send_to_address(address, send_amount, fee_rate_opt, None, &self.channel_manager)
	}

	/// Create and submit a fixed-amount on-chain send through one direct backend route.
	///
	/// `Err` proves this invocation did not start broadcast. `Rejected` and `Unknown` both
	/// retain the txid and do not authorize another payment. This does not wait for confirmation.
	/// Current-thread Tokio callers receive [`Error::PaymentSendingFailed`] before wallet preparation.
	pub fn send_to_address_with_broadcast_result(
		&self, address: &bitcoin::Address, amount_sats: u64, fee_rate: Option<FeeRate>,
		utxos_to_spend: Option<Vec<SpendableUtxo>>,
	) -> Result<OnchainSendResult, Error> {
		let reserve =
			crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);
		let amount = OnchainSendAmount::ExactRetainingReserve {
			amount_sats,
			cur_anchor_reserve_sats: reserve,
		};
		let outpoints = utxos_to_spend.map(|utxos| utxos.into_iter().map(|u| u.outpoint).collect());
		self.send_with_broadcast_result(address, amount, fee_rate, outpoints)
	}

	/// Create and submit a send-all transaction through one direct backend route.
	///
	/// The reserve behavior matches [`Self::send_all_to_address`]. `Err` is limited to a proven
	/// pre-dispatch failure. Any attempted submission returns its txid, even if unresolved.
	/// Current-thread Tokio callers receive [`Error::PaymentSendingFailed`] before wallet preparation.
	pub fn send_all_to_address_with_broadcast_result(
		&self, address: &bitcoin::Address, retain_reserves: bool, fee_rate: Option<FeeRate>,
	) -> Result<OnchainSendResult, Error> {
		let amount = if retain_reserves {
			let reserve =
				crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);
			OnchainSendAmount::AllRetainingReserve { cur_anchor_reserve_sats: reserve }
		} else {
			OnchainSendAmount::AllDrainingReserve
		};
		self.send_with_broadcast_result(address, amount, fee_rate, None)
	}

	/// Prepare a fixed-amount candidate without backend submission.
	///
	/// With explicit inputs, requires a nonempty unique wallet-unspent set and verifies the
	/// signed transaction spends exactly that set. None permits initial automatic selection.
	/// Persist the actual candidate receipt under the original payment identity before broadcast.
	/// Recovery must pass the ORIGINAL input set and recipient amount, never fresh selection.
	/// If the signed recipient-script output sum differs from `amount_sats` (for example,
	/// when the recipient aliases change), returns `OnchainTxCreationFailed` before dispatch.
	pub fn prepare_send_to_address(
		&self, address: &Address, amount_sats: u64, fee_rate: Option<FeeRate>,
		utxos_to_spend: Option<Vec<SpendableUtxo>>,
	) -> Result<Arc<PreparedOnchainSend>, Error> {
		let reserve =
			crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);
		let prepared = self.prepare_send(
			address,
			OnchainSendAmount::ExactRetainingReserve {
				amount_sats,
				cur_anchor_reserve_sats: reserve,
			},
			fee_rate,
			utxos_to_spend.map(|utxos| utxos.into_iter().map(|u| u.outpoint).collect()),
		)?;
		// Reject a recipient/change alias rather than hand the caller a different fixed amount.
		if prepared.recipient_amount_sats() != amount_sats {
			return Err(Error::OnchainTxCreationFailed);
		}
		Ok(prepared)
	}

	/// Prepare an initial send-all candidate with the existing drain/reserve behavior.
	///
	/// This does not dispatch. Persist its actual signed inputs, txid and recipient amount
	/// under the original payment identity before broadcast. Recovery successors must use
	/// fixed preparation with that ORIGINAL amount and exact input set, never another drain.
	pub fn prepare_send_all_to_address(
		&self, address: &Address, retain_reserves: bool, fee_rate: Option<FeeRate>,
	) -> Result<Arc<PreparedOnchainSend>, Error> {
		let amount = if retain_reserves {
			let reserve =
				crate::total_anchor_channels_reserve_sats(&self.channel_manager, &self.config);
			OnchainSendAmount::AllRetainingReserve { cur_anchor_reserve_sats: reserve }
		} else {
			OnchainSendAmount::AllDrainingReserve
		};
		self.prepare_send(address, amount, fee_rate, None)
	}

	/// Bumps the fee of an existing transaction using Replace-By-Fee (RBF).
	///
	/// This allows a previously sent transaction to be replaced with a new version
	/// that pays a higher fee. The original transaction must have been created with
	/// RBF enabled (which is the default for transactions created by LDK).
	///
	/// **Note:** This cannot be used on funding transactions as doing so would invalidate the channel.
	///
	/// # Arguments
	///
	/// * `txid` - The transaction ID of the transaction to be replaced
	/// * `fee_rate` - The new fee rate to use (must be higher than the original fee rate)
	///
	/// # Returns
	///
	/// The transaction ID of the new transaction if successful.
	///
	/// # Errors
	///
	/// * [`Error::NotRunning`] - If the node is not running
	/// * [`Error::TransactionNotFound`] - If the transaction can't be found in the wallet
	/// * [`Error::TransactionAlreadyConfirmed`] - If the transaction is already confirmed
	/// * [`Error::CannotRbfFundingTransaction`] - If the transaction is a channel funding transaction
	/// * [`Error::InvalidFeeRate`] - If the new fee rate is not higher than the original
	/// * [`Error::OnchainTxCreationFailed`] - If the new transaction couldn't be created
	pub fn bump_fee_by_rbf(&self, txid: &Txid, fee_rate: FeeRate) -> Result<Txid, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		// Pass through to the wallet implementation
		#[cfg(not(feature = "uniffi"))]
		let fee_rate_param = fee_rate;
		#[cfg(feature = "uniffi")]
		let fee_rate_param = *fee_rate;

		self.wallet.bump_fee_by_rbf(txid, fee_rate_param, &self.channel_manager)
	}

	/// Accelerates confirmation of a transaction using Child-Pays-For-Parent (CPFP).
	///
	/// This creates a new transaction (child) that spends an output from the
	/// transaction to be accelerated (parent), with a high enough fee to pay for both.
	///
	/// # Arguments
	///
	/// * `txid` - The transaction ID of the transaction to be accelerated
	/// * `fee_rate` - The fee rate to use for the child transaction (or None to calculate automatically)
	/// * `destination_address` - Optional address to send the funds to (if None, funds are sent to an internal address)
	///
	/// # Returns
	///
	/// The transaction ID of the child transaction if successful.
	///
	/// # Errors
	///
	/// * [`Error::NotRunning`] - If the node is not running
	/// * [`Error::TransactionNotFound`] - If the transaction can't be found
	/// * [`Error::TransactionAlreadyConfirmed`] - If the transaction is already confirmed
	/// * [`Error::NoSpendableOutputs`] - If the transaction has no spendable outputs
	/// * [`Error::OnchainTxCreationFailed`] - If the child transaction couldn't be created
	pub fn accelerate_by_cpfp(
		&self, txid: &Txid, fee_rate: Option<FeeRate>, destination_address: Option<Address>,
	) -> Result<Txid, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		// Calculate fee rate if not provided
		#[cfg(not(feature = "uniffi"))]
		let fee_rate_param = match fee_rate {
			Some(rate) => rate,
			None => self.wallet.calculate_cpfp_fee_rate(txid, true)?,
		};

		#[cfg(feature = "uniffi")]
		let fee_rate_param = match fee_rate {
			Some(rate) => *rate,
			None => self.wallet.calculate_cpfp_fee_rate(txid, true)?,
		};

		// Pass through to the wallet implementation
		self.wallet.accelerate_by_cpfp(txid, fee_rate_param, destination_address)
	}

	/// Calculates an appropriate fee rate for a CPFP transaction to ensure
	/// the parent transaction gets confirmed within the target number of blocks.
	///
	/// This method analyzes the parent transaction's current fee rate and calculates
	/// how much the child transaction needs to pay to bring the combined package
	/// fee rate up to the target level.
	///
	/// # Arguments
	///
	/// * `parent_txid` - The transaction ID of the parent transaction to accelerate
	/// * `urgent` - If true, uses a more aggressive fee rate for faster confirmation
	///
	/// # Returns
	///
	/// The fee rate that should be used for the child transaction.
	///
	/// # Errors
	///
	/// * [`Error::NotRunning`] - If the node is not running
	/// * [`Error::TransactionNotFound`] - If the parent transaction can't be found
	/// * [`Error::TransactionAlreadyConfirmed`] - If the parent transaction is already confirmed
	/// * [`Error::WalletOperationFailed`] - If fee calculation fails
	pub fn calculate_cpfp_fee_rate(
		&self, parent_txid: &Txid, urgent: bool,
	) -> Result<FeeRate, Error> {
		if !*self.is_running.read().unwrap() {
			return Err(Error::NotRunning);
		}

		let fee_rate = self.wallet.calculate_cpfp_fee_rate(parent_txid, urgent)?;

		#[cfg(not(feature = "uniffi"))]
		{
			Ok(fee_rate)
		}
		#[cfg(feature = "uniffi")]
		{
			Ok(Arc::new(fee_rate))
		}
	}
}

#[cfg(all(test, not(feature = "uniffi")))]
mod prepared_send_tests {
	use super::*;
	use bitcoin::hashes::Hash;
	use bitcoin::{absolute, transaction, Amount, Network, TxIn, TxOut};
	use std::io::{Read, Write};
	use std::net::TcpListener;
	use std::time::Duration;

	struct Fixture {
		node: crate::Node,
		listener: TcpListener,
	}

	impl Fixture {
		fn new() -> Self {
			let listener = TcpListener::bind("127.0.0.1:0").unwrap();
			listener.set_nonblocking(true).unwrap();
			let dir = std::env::temp_dir().join(format!("ldk-prepared-{}", rand::random::<u64>()));
			let config = Config {
				storage_dir_path: dir.to_str().unwrap().to_owned(),
				network: Network::Regtest,
				include_untrusted_pending_in_spendable: true,
				..Default::default()
			};
			let mut builder = crate::Builder::from_config(config);
			builder.set_chain_source_esplora(
				format!("http://{}", listener.local_addr().unwrap()),
				Some(crate::config::EsploraSyncConfig { background_sync_config: None }),
			);
			let node = builder.build().unwrap();
			// Exercise signing and direct dispatch without starting any background sync tasks.
			*node.is_running.write().unwrap() = true;
			let address = node.onchain_payment().new_address().unwrap();
			let funding = Transaction {
				version: transaction::Version::TWO,
				lock_time: absolute::LockTime::ZERO,
				input: vec![TxIn {
					previous_output: OutPoint { txid: Txid::from_byte_array([42; 32]), vout: 0 },
					..Default::default()
				}],
				output: [100_000, 200_000]
					.into_iter()
					.map(|value| TxOut {
						value: Amount::from_sat(value),
						script_pubkey: address.script_pubkey(),
					})
					.collect(),
			};
			node.wallet.apply_mempool_txs(vec![(funding, 1)], vec![]).unwrap();
			Self { node, listener }
		}

		fn recipient(&self) -> Address {
			// An external script distinct from this fixture's wallet/change addresses.
			Address::p2wsh(&bitcoin::ScriptBuf::new(), Network::Regtest)
		}

		fn assert_no_dispatch(&self) {
			assert_eq!(self.listener.accept().unwrap_err().kind(), std::io::ErrorKind::WouldBlock);
		}
	}

	impl Drop for Fixture {
		fn drop(&mut self) {
			*self.node.is_running.write().unwrap() = false;
		}
	}

	fn fee() -> Option<FeeRate> {
		Some(bitcoin::FeeRate::from_sat_per_vb_u32(2))
	}

	#[test]
	fn prepared_receipt_and_fixed_successors_use_exact_original_inputs() {
		let f = Fixture::new();
		let payment = f.node.onchain_payment();
		let original = payment.list_spendable_outputs().unwrap()[..1].to_vec();
		let prepared = payment
			.prepare_send_to_address(&f.recipient(), 50_000, fee(), Some(original.clone()))
			.unwrap();
		assert_eq!(prepared.inputs(), vec![original[0].outpoint]);
		assert_eq!(prepared.txid(), prepared.tx.compute_txid());
		assert_eq!(prepared.recipient_amount_sats(), 50_000);
		assert!(prepared.tx.input.iter().all(|input| !input.witness.is_empty()));
		let successor = payment
			.prepare_send_to_address(
				&f.recipient(),
				prepared.recipient_amount_sats(),
				Some(bitcoin::FeeRate::from_sat_per_vb_u32(3)),
				Some(original),
			)
			.unwrap();
		assert_eq!(successor.inputs(), prepared.inputs());
		assert_eq!(successor.recipient_amount_sats(), prepared.recipient_amount_sats());
		assert_ne!(successor.txid(), prepared.txid());
		// Signing did not insert either outgoing transaction or consume the original inputs.
		assert_eq!(payment.list_spendable_outputs().unwrap().len(), 2);
		drop(prepared);
		drop(successor);
		f.assert_no_dispatch();
	}

	#[test]
	fn prepared_initial_max_preserves_native_drain_and_reserve_amounts() {
		let f = Fixture::new();
		let payment = f.node.onchain_payment();
		let address = f.recipient();
		for retain_reserves in [false, true] {
			let prepared =
				payment.prepare_send_all_to_address(&address, retain_reserves, fee()).unwrap();
			let legacy = payment
				.wallet
				.prepare_send_to_address(
					&address,
					OnchainSendAmount::AllDrainingReserve,
					fee(),
					None,
					&payment.channel_manager,
				)
				.unwrap();
			assert_eq!(prepared.tx.output, legacy.output);
			assert_eq!(
				prepared.inputs().into_iter().collect::<HashSet<_>>(),
				legacy.input.iter().map(|i| i.previous_output).collect()
			);
			assert_eq!(prepared.inputs().len(), 2);
			assert_eq!(prepared.recipient_amount_sats(), legacy.output[0].value.to_sat());
			let original_inputs = prepared
				.inputs()
				.into_iter()
				.map(|outpoint| SpendableUtxo { outpoint, value_sats: 0 })
				.collect();
			let recovery = payment
				.prepare_send_to_address(
					&address,
					prepared.recipient_amount_sats(),
					fee(),
					Some(original_inputs),
				)
				.unwrap();
			assert_eq!(
				recovery.inputs().into_iter().collect::<HashSet<_>>(),
				prepared.inputs().into_iter().collect()
			);
			assert_eq!(recovery.recipient_amount_sats(), prepared.recipient_amount_sats());
		}
		// Cover the same retained-reserve branch with a nonzero reserve, without channel fixtures.
		let amount = OnchainSendAmount::AllRetainingReserve { cur_anchor_reserve_sats: 20_000 };
		let legacy = payment
			.wallet
			.prepare_send_to_address(&address, amount, fee(), None, &payment.channel_manager)
			.unwrap();
		let prepared = payment.prepare_send(&address, amount, fee(), None).unwrap();
		let recipient_value: u64 = legacy
			.output
			.iter()
			.filter(|out| out.script_pubkey == address.script_pubkey())
			.map(|out| out.value.to_sat())
			.sum();
		assert_eq!(prepared.recipient_amount_sats(), recipient_value);
		assert_eq!(prepared.inputs().len(), legacy.input.len());
		assert!(
			prepared
				.tx
				.output
				.iter()
				.filter(|out| out.script_pubkey != address.script_pubkey())
				.map(|out| out.value.to_sat())
				.sum::<u64>()
				>= 20_000
		);
		// A Max receipt leaves no fee headroom in its original inputs. Even if new
		// wallet funds arrive, recovery must not add them or reduce the merchant amount.
		let original_max = payment.prepare_send_all_to_address(&address, false, fee()).unwrap();
		let original_amount = original_max.recipient_amount_sats();
		let original_inputs: Vec<_> = original_max
			.inputs()
			.into_iter()
			.map(|outpoint| SpendableUtxo { outpoint, value_sats: 0 })
			.collect();
		let additional_address = payment.new_address().unwrap();
		let additional_funding = Transaction {
			version: transaction::Version::TWO,
			lock_time: absolute::LockTime::ZERO,
			input: vec![TxIn {
				previous_output: OutPoint { txid: Txid::from_byte_array([43; 32]), vout: 0 },
				..Default::default()
			}],
			output: vec![TxOut {
				value: Amount::from_sat(1_000_000),
				script_pubkey: additional_address.script_pubkey(),
			}],
		};
		payment.wallet.apply_mempool_txs(vec![(additional_funding, 3)], vec![]).unwrap();
		assert_eq!(payment.list_spendable_outputs().unwrap().len(), 3);
		let higher_fee = Some(bitcoin::FeeRate::from_sat_per_vb_u32(3));
		assert_eq!(
			payment
				.prepare_send_to_address(
					&address,
					original_amount,
					higher_fee,
					Some(original_inputs)
				)
				.err(),
			Some(Error::InsufficientFunds)
		);
		// Fresh automatic selection could pay it, proving the explicit set did not fall back.
		let unconstrained =
			payment.prepare_send_to_address(&address, original_amount, higher_fee, None).unwrap();
		assert_eq!(unconstrained.recipient_amount_sats(), original_amount);
		assert!(unconstrained.inputs().iter().any(|input| !original_max.inputs().contains(input)));
		assert_eq!(original_max.recipient_amount_sats(), original_amount);
		f.assert_no_dispatch();
	}

	#[test]
	fn prepared_fixed_rejects_recipient_change_alias_amount_mismatch() {
		let f = Fixture::new();
		let payment = f.node.onchain_payment();
		let change_script = payment.wallet.get_drain_script().unwrap();
		let recipient = Address::from_script(&change_script, Network::Regtest).unwrap();
		assert_eq!(
			payment.prepare_send_to_address(&recipient, 50_000, fee(), None).err(),
			Some(Error::OnchainTxCreationFailed)
		);
		f.assert_no_dispatch();
	}

	#[test]
	fn prepared_invalid_inputs_fail_before_dispatch_without_auto_fallback() {
		let f = Fixture::new();
		let payment = f.node.onchain_payment();
		let original = payment.list_spendable_outputs().unwrap()[0].clone();
		for inputs in [
			vec![],
			vec![original.clone(), original.clone()],
			vec![SpendableUtxo {
				outpoint: OutPoint { txid: Txid::from_byte_array([99; 32]), vout: 0 },
				value_sats: 1_000_000,
			}],
		] {
			assert!(payment
				.prepare_send_to_address(&f.recipient(), 50_000, fee(), Some(inputs))
				.is_err());
		}
		let mut fake_hint = original.clone();
		fake_hint.value_sats = u64::MAX;
		assert!(payment
			.prepare_send_to_address(&f.recipient(), 250_000, fee(), Some(vec![fake_hint]))
			.is_err());
		let mut tx = payment
			.prepare_send_to_address(&f.recipient(), 50_000, fee(), Some(vec![original.clone()]))
			.unwrap()
			.tx
			.clone();
		// Positive wallet observation of a spend invalidates the original input even though
		// another wallet UTXO could fund the payment; manual selection must never fall back.
		payment.wallet.apply_mempool_txs(vec![(tx.clone(), 2)], vec![]).unwrap();
		assert!(payment
			.prepare_send_to_address(&f.recipient(), 50_000, fee(), Some(vec![original.clone()]))
			.is_err());
		tx.input[0].previous_output = OutPoint::null();
		assert_eq!(
			validate_signed_inputs(&tx, &[original.outpoint]),
			Err(Error::OnchainTxCreationFailed)
		);
		f.assert_no_dispatch();
	}

	#[test]
	fn prepared_context_errors_precede_preparation_and_dispatch() {
		let f = Fixture::new();
		let payment = f.node.onchain_payment();
		let prepared =
			payment.prepare_send_to_address(&f.recipient(), 50_000, fee(), None).unwrap();
		let runtime = tokio::runtime::Builder::new_current_thread().enable_all().build().unwrap();
		runtime.block_on(async {
			assert_eq!(
				payment.prepare_send_to_address(&f.recipient(), 50_000, fee(), None).err(),
				Some(Error::PaymentSendingFailed)
			);
			assert_eq!(
				payment.prepare_send_all_to_address(&f.recipient(), false, fee()).err(),
				Some(Error::PaymentSendingFailed)
			);
			assert_eq!(prepared.broadcast(), Err(Error::PaymentSendingFailed));
		});
		*f.node.is_running.write().unwrap() = false;
		assert_eq!(prepared.broadcast(), Err(Error::NotRunning));
		assert_eq!(
			payment.prepare_send_to_address(&f.recipient(), 50_000, fee(), None).err(),
			Some(Error::NotRunning)
		);
		f.assert_no_dispatch();
	}

	#[test]
	fn prepared_broadcast_serializes_callers_and_caches_each_backend_result() {
		for (status, body_kind) in [(200, "accepted"), (400, "rejected"), (200, "unknown")] {
			let f = Fixture::new();
			let prepared = f
				.node
				.onchain_payment()
				.prepare_send_to_address(&f.recipient(), 50_000, fee(), None)
				.unwrap();
			f.assert_no_dispatch();
			let listener = f.listener.try_clone().unwrap();
			listener.set_nonblocking(false).unwrap();
			let expected_body = bitcoin::consensus::encode::serialize_hex(&prepared.tx);
			let txid = prepared.txid();
			let server = std::thread::spawn(move || {
				let (mut stream, _) = listener.accept().unwrap();
				stream.set_read_timeout(Some(Duration::from_secs(5))).unwrap();
				let mut request = Vec::new();
				let header_end = loop {
					let mut byte = [0u8; 1];
					stream.read_exact(&mut byte).unwrap();
					request.push(byte[0]);
					if request.ends_with(b"\r\n\r\n") {
						break request.len();
					}
				};
				let headers = String::from_utf8(request[..header_end].to_vec()).unwrap();
				assert!(headers.starts_with("POST /tx HTTP/1.1"));
				let len: usize = headers
					.lines()
					.find_map(|line| {
						line.to_ascii_lowercase()
							.strip_prefix("content-length: ")
							.map(str::to_owned)
					})
					.unwrap()
					.parse()
					.unwrap();
				let mut bytes = vec![0u8; len];
				stream.read_exact(&mut bytes).unwrap();
				assert_eq!(String::from_utf8(bytes).unwrap(), expected_body);
				let body = match body_kind {
					"accepted" => txid.to_string(),
					"rejected" => {
						"sendrawtransaction RPC error: {\"code\":-26,\"message\":\"non-final\"}"
							.to_owned()
					},
					_ => "malformed".to_owned(),
				};
				write!(
					stream,
					"HTTP/1.1 {} result\r\nContent-Length: {}\r\nConnection: close\r\n\r\n{}",
					status,
					body.len(),
					body
				)
				.unwrap();
			});
			let other = Arc::clone(&prepared);
			let concurrent = std::thread::spawn(move || other.broadcast());
			let result = prepared.broadcast().unwrap();
			assert_eq!(concurrent.join().unwrap().unwrap(), result);
			assert_eq!(prepared.broadcast().unwrap(), result);
			assert!(match body_kind {
				"accepted" =>
					matches!(result, OnchainSendResult::Accepted { txid: id } if id == txid),
				"rejected" =>
					matches!(result, OnchainSendResult::Rejected { txid: id, .. } if id == txid),
				_ => matches!(result, OnchainSendResult::Unknown { txid: id } if id == txid),
			});
			server.join().unwrap();
			f.listener.set_nonblocking(true).unwrap();
			f.assert_no_dispatch();
		}
	}
}
